version: 2.1

jobs:
  tests:
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: typless
          POSTGRES_PASSWORD: typless
          POSTGRES_DB: typless
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "typless_backend/requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            pip install --user -r typless_backend/requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "typless_backend/requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run: python manage.py test

workflows:
  main:
    jobs:
      - tests